package com.ppublica.stargazer.spotpersonalizationservice.spotpersonalization.application.usecase.initializespotpersonalization;

import com.ppublica.stargazer.spotpersonalizationservice.spotpersonalization.application.view.SpotPersonalizationView;

public interface InitializeSpotPersonalizationUseCase {
    SpotPersonalizationView handle(InitializeSpotPersonalizationCommand command);
}
