package com.ppublica.stargazer.spotpersonalizationservice.spotpersonalization.application.usecase.clearskyvisibilitybucket;

import com.ppublica.stargazer.spotpersonalizationservice.spotpersonalization.domain.model.SpotPersonalizationId;

public record ClearSkyVisibilityBucketCommand(SpotPersonalizationId id) {}
